In [1]:
import pandas as pd
import numpy as np

class Partitioner:
    def __init__(self):
        pass

    def assign_continuous_partition_values(df, n_paritions, partition_column, ratio=None) -> pd.DataFrame:
        """
        Assigns continuous partition values to a DataFrame.
        
        This function partitions a DataFrame into a specified number of partitions or 
        based on a partition ratio. The partition values are assigned to a new column 
        in the DataFrame.
        
        Parameters:
        - `df (pd.DataFrame)`: The DataFrame to be partitioned.
        - `n_paritions (int)`: The number of partitions to create.
        - `partition_column (str)`: The name of the column to store partition values.
        - `ratio (float, optional)`: The ratio of the DataFrame to be partitioned. 
                                           If provided, it overrides n_paritions.
        
        Returns:
        `pd.DataFrame`: The DataFrame with an additional column containing partition values.
        Raises:
        AssertionError: If n_paritions is not between 1 and the length of the DataFrame.
        """

        if ratio is not None:
            n_paritions = int(len(df) * ratio)
            
        assert 0 < n_paritions <= len(df), "The number of partitions must be between 1 and the length of the dataframe."
        cut_points = [0] + sorted(np.random.choice(range(1, len(df)- 1), n_paritions - 1, replace=False)) + [len(df)]
        
        
        df[partition_column] = pd.cut(df.index, bins=cut_points, labels=range(n_paritions))
        return df


    def group_partition(df, group_column, value_column, delimiter):
        """
        Group the values in the value_column by the group_column.
        
        Parameters:
        - `df (pandas.DataFrame)`: The DataFrame containing the data to be grouped.
        - `group_column (str)`: The column name to group by.
        - `value_column (str)`: The column name whose values will be grouped.
        - `delimiter (str or None)`: The delimiter to use for joining the grouped values. 
                                 If None, the values will be grouped into a list.
        Returns:
        `pandas.DataFrame`: A DataFrame with the grouped values.
        """
        if delimiter is None:
            grouped = df.groupby(group_column)[value_column].apply(list).reset_index()
        else:
            grouped = df.groupby(group_column)[value_column].apply(lambda x: delimiter.join(map(str, x))).reset_index()
        return grouped

In [4]:
# demo

# Create a sample DataFrame
data = {'A': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 'B': [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]}
df = pd.DataFrame(data)

# Assign continuous partition values
df = Partitioner.assign_continuous_partition_values(df, 5, 'partition')

# Group the valuesd in column 'B' by the partition values
grouped = Partitioner.group_partition(df, 'partition', 'B', delimiter=',')

print(grouped)

  partition         B
0         0     12,13
1         1        14
2         2        15
3         3  16,17,18
4         4     19,20

C:\Users\Admin\AppData\Local\Temp\ipykernel_14148\2530702606.py:56: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grouped = df.groupby(group_column)[value_column].apply(lambda x: delimiter.join(map(str, x))).reset_index()

In [36]:
# demo

# Create a sample DataFrame
data = {'A': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 'B': [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]}
df = pd.DataFrame(data)
print(df)
# Assign continuous partition values
df = Partitioner.assign_continuous_partition_values(df, 5, 'partition')

# Group the values in column 'B' by the partition values
grouped = Partitioner.group_partition(df, 'partition', 'B', delimiter=',')

print(grouped)

    A   B
0   1  11
1   2  12
2   3  13
3   4  14
4   5  15
5   6  16
6   7  17
7   8  18
8   9  19
9  10  20
  partition            B
0         0           12
1         1  13,14,15,16
2         2           17
3         3        18,19
4         4           20

C:\Users\Admin\AppData\Local\Temp\ipykernel_14148\2530702606.py:56: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grouped = df.groupby(group_column)[value_column].apply(lambda x: delimiter.join(map(str, x))).reset_index()

In [1]:
import pandas as pd 

df_sentences = pd.read_excel("E:\\study 7\\NLP\\CK\\Data\\data_sentences.xlsx")
df_sentences

,Index,Source,Text,Character
0,1,https://chunom.org/shelf/corpus/1/,埃 喂 傷 𥙩 饒 穷,Nom
1,2,https://chunom.org/shelf/corpus/1/,𨕭 頭 畧 㩫 簮 掑,Nom
2,3,https://chunom.org/shelf/corpus/1/,𥪝 𠀧 𨑮 𦒹 傳 英 攝 固 𨱽 𫨩 空,Nom
3,4,https://chunom.org/shelf/corpus/1/,欺 𢧚 𡗶 拱 朝 𢚸 奇 𠄩,Nom
4,5,https://chunom.org/shelf/corpus/1/,題 𠸜 𡭉 鵲 縁 𡗶 𦓡 𢧚,Nom
...,...,...,...,...
76772,76773,thivien_Phan-Văn-Ái_Hương-Sơn-thi_raw.html,長 帶 天 香 滿 袖 還,Chinese
76773,76774,thivien_Nguyễn-Sưởng_Nguyệt-trung-quế_raw.html,雲 栽 露 種 已 多 時,Chinese
76774,76775,thivien_Nguyễn-Sưởng_Nguyệt-trung-quế_raw.html,清 影 婆 娑 看 轉 奇,Chinese
76775,76776,thivien_Nguyễn-Sưởng_Nguyệt-trung-quế_raw.html,可 是 姮 娥 偏 愛 惜,Chinese
76776,76777,thivien_Nguyễn-Sưởng_Nguyệt-trung-quế_raw.html,肯 教 輪 外 放 長 枝,Chinese

In [2]:
import os
import sys
sys.path.append(os.path.join('../'))
from utils.dataframe_preprocessing import load_and_clean_data

df_sentences = load_and_clean_data("E:\\study 7\\NLP\\CK\\Data\\data_sentences.xlsx")
df_sentences

,Index,Source,sentence,Label,sentence_cleaned,BinaryLabel
0,1,https://chunom.org/shelf/corpus/1/,埃 喂 傷 𥙩 饒 穷,Nom,埃喂傷𥙩饒穷,1
1,2,https://chunom.org/shelf/corpus/1/,𨕭 頭 畧 㩫 簮 掑,Nom,𨕭頭畧㩫簮掑,1
2,3,https://chunom.org/shelf/corpus/1/,𥪝 𠀧 𨑮 𦒹 傳 英 攝 固 𨱽 𫨩 空,Nom,𥪝𠀧𨑮𦒹傳英攝固𨱽𫨩空,1
3,4,https://chunom.org/shelf/corpus/1/,欺 𢧚 𡗶 拱 朝 𢚸 奇 𠄩,Nom,欺𢧚𡗶拱朝𢚸奇𠄩,1
4,5,https://chunom.org/shelf/corpus/1/,題 𠸜 𡭉 鵲 縁 𡗶 𦓡 𢧚,Nom,題𠸜𡭉鵲縁𡗶𦓡𢧚,1
...,...,...,...,...,...,...
76772,76773,thivien_Phan-Văn-Ái_Hương-Sơn-thi_raw.html,長 帶 天 香 滿 袖 還,Chinese,長帶天香滿袖還,0
76773,76774,thivien_Nguyễn-Sưởng_Nguyệt-trung-quế_raw.html,雲 栽 露 種 已 多 時,Chinese,雲栽露種已多時,0
76774,76775,thivien_Nguyễn-Sưởng_Nguyệt-trung-quế_raw.html,清 影 婆 娑 看 轉 奇,Chinese,清影婆娑看轉奇,0
76775,76776,thivien_Nguyễn-Sưởng_Nguyệt-trung-quế_raw.html,可 是 姮 娥 偏 愛 惜,Chinese,可是姮娥偏愛惜,0
76776,76777,thivien_Nguyễn-Sưởng_Nguyệt-trung-quế_raw.html,肯 教 輪 外 放 長 枝,Chinese,肯教輪外放長枝,0

In [3]:
df_sentences = pd.DataFrame({
    'source': df_sentences['Source'],
    'sentence': df_sentences['sentence_cleaned'],
    'label': df_sentences['Label']
})

df_sentences.to_csv("../data/data_sentences.csv", index=False)

In [12]:
# show the rows that a source has less than 4 sentences and remove them
df_sentences = df_sentences.groupby('source').filter(lambda x: len(x) >= 4)

In [13]:
df_sentences.to_csv("../data/data_sentences.csv", index=False)

In [13]:
df_sentences['Source'].value_counts()

Source
vi-du-tu-dien-dan-giai-nf.no.txt                        19974
dvsktt                                                  19218
thien-nam-ngu-luc.no.txt                                 8235
7_corpus-documents-chunomOrg_no.txt                      3524
3_tale-of-kieu_no.txt                                    3276
                                                        ...
https://chunom.org/shelf/corpus/20/                         2
thivien_Hoàng-Trọng-Mậu_Ngục-trung-cảm-thán_raw.html        2
https://chunom.org/shelf/corpus/111/                        1
https://chunom.org/shelf/corpus/22/                         1
https://chunom.org/shelf/corpus/127/                        1
Name: count, Length: 492, dtype: int64

In [6]:
df_sentences.info()

<class 'pandas.core.frame.DataFrame'>
Index: 76739 entries, 0 to 76776
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   source    76739 non-null  object
 1   sentence  76739 non-null  object
 2   label     76739 non-null  object
dtypes: object(3)
memory usage: 2.3+ MB

In [9]:
df_sentences = df_sentences[df_sentences['sentence'].apply(lambda x: isinstance(x, str))]

In [10]:
df_sentences.info()

<class 'pandas.core.frame.DataFrame'>
Index: 76739 entries, 0 to 76776
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   source    76739 non-null  object
 1   sentence  76739 non-null  object
 2   label     76739 non-null  object
dtypes: object(3)
memory usage: 2.3+ MB

In [20]:
# create a new dataframe with one source have a list of sentences
df_article = pd.DataFrame(df_sentences.groupby('Source')['sentence_cleaned'].apply(list)).reset_index()
# map the label from df_sentences to df_article based on the source
for source in df_sentences['Source'].unique():
    label = df_sentences[df_sentences['Source'] == source]['Label'].values[0]
    df_article.loc[df_article['Source'] == source, 'Label'] = label

df_article

,Source,sentence_cleaned,Label
0,10-bai-ke-trich-thap-gioi-co-hon-van.no.txt,"[偈嘆哴, 蔑瓶蔑鉢蔑袈裟, 耨於廛伽𨴦茹, 經㐌玊楼香論篆, 定退禪院俸磋花, 身心瀝...",Nom
1,10_nu-tu-tri_no.txt,"[吀𦖑㛪分觧𠳒尼, 𢢇勾十女朱󰎾曰無, 㤙生養似乎𡽫泰, 捔𬚸昌庫𢚶報𡊰, 虎拱男子偪𨕭, ...",Nom
2,11_di-cho-tinh-tien_no.txt,"[吝巾如注半𪃴, 錢𥙪空半半𠀧𨒒銅, 𠫾𢄂併錢, 沒貫錢卒忙𠫾, 錢𥙪𥺊𥻻貝𠀧銅𦺓, 錢𥙪𠰳...",Nom
3,12_giao-tu-phu_no.txt,"[教子賦, 一切升沉, 生𩔗五濁, 爲𢚸爲胣, 傷丐傷𡥵, 𠺥庫𣎀𣈗, 㐌時時南, 争欣争舌...",Nom
4,13_tho-hong-kieu_no.txt,"[重簾不捲日昏黃, 絡繹啼來也斷腸, 幾度繫書君不答, 雁飛應未到衡陽, 象牙筠簟碧紗籠, ...",Nom
...,...,...,...
487,thivien_Đặng-Đề_Đặng-Lặc-dịch_raw.html,"[驛名磴勒亦龍州, 石嶺連延水路紆, 別有武盈佳景致, 林窮山盡見平蕪]",Chinese
488,thivien_Đỗ-Khắc-Chung_Vịnh-cúc-kỳ-2_raw.html,"[重陽摘蕊陶攘醉, 秋夕餐英屈愛香, 二老風流千載遠, 天教菊隱出承當]",Chinese
489,tung-tay-ho-phu.no.txt,"[邏処景西湖, 邏処景西湖, 謭仌挆坦勚佂憥, 牐浪低廏仺沒潄, 苉白猢侟於刬乄缊龍王阻戼潂...",Nom
490,van-te-giao-su-nguyen-khac-nham-drop-5-line.no...,"[敬𠽔偨𠽔偨, 羅們生𡤓壹, 偨愴𠰺過𡗊, 窖𠸕𠻀𡗋役, 㝹佛學文學, 𡦂喃拱字漢, 朱立雉...",Nom
491,vi-du-tu-dien-dan-giai-nf.no.txt,"[󱳌創𦊚競󰑼𬁖孛, 󰰀擼󰜋方󰑼𬁖彗, 𡥵𤤰辰吏爫𤤰, 𡥵茄柴𫴶辰撅𦲿栘, 眉𫽄󱫩些時些吏𧿨衛...",Nom

In [22]:
df_article.rename(columns={'sentence_cleaned': 'sentences'}, inplace=True)
df_article.to_csv("../Data/data_articles.csv", index=False)

In [23]:
df_article

,Source,sentences,Label
0,10-bai-ke-trich-thap-gioi-co-hon-van.no.txt,"[偈嘆哴, 蔑瓶蔑鉢蔑袈裟, 耨於廛伽𨴦茹, 經㐌玊楼香論篆, 定退禪院俸磋花, 身心瀝...",Nom
1,10_nu-tu-tri_no.txt,"[吀𦖑㛪分觧𠳒尼, 𢢇勾十女朱󰎾曰無, 㤙生養似乎𡽫泰, 捔𬚸昌庫𢚶報𡊰, 虎拱男子偪𨕭, ...",Nom
2,11_di-cho-tinh-tien_no.txt,"[吝巾如注半𪃴, 錢𥙪空半半𠀧𨒒銅, 𠫾𢄂併錢, 沒貫錢卒忙𠫾, 錢𥙪𥺊𥻻貝𠀧銅𦺓, 錢𥙪𠰳...",Nom
3,12_giao-tu-phu_no.txt,"[教子賦, 一切升沉, 生𩔗五濁, 爲𢚸爲胣, 傷丐傷𡥵, 𠺥庫𣎀𣈗, 㐌時時南, 争欣争舌...",Nom
4,13_tho-hong-kieu_no.txt,"[重簾不捲日昏黃, 絡繹啼來也斷腸, 幾度繫書君不答, 雁飛應未到衡陽, 象牙筠簟碧紗籠, ...",Nom
...,...,...,...
487,thivien_Đặng-Đề_Đặng-Lặc-dịch_raw.html,"[驛名磴勒亦龍州, 石嶺連延水路紆, 別有武盈佳景致, 林窮山盡見平蕪]",Chinese
488,thivien_Đỗ-Khắc-Chung_Vịnh-cúc-kỳ-2_raw.html,"[重陽摘蕊陶攘醉, 秋夕餐英屈愛香, 二老風流千載遠, 天教菊隱出承當]",Chinese
489,tung-tay-ho-phu.no.txt,"[邏処景西湖, 邏処景西湖, 謭仌挆坦勚佂憥, 牐浪低廏仺沒潄, 苉白猢侟於刬乄缊龍王阻戼潂...",Nom
490,van-te-giao-su-nguyen-khac-nham-drop-5-line.no...,"[敬𠽔偨𠽔偨, 羅們生𡤓壹, 偨愴𠰺過𡗊, 窖𠸕𠻀𡗋役, 㝹佛學文學, 𡦂喃拱字漢, 朱立雉...",Nom
491,vi-du-tu-dien-dan-giai-nf.no.txt,"[󱳌創𦊚競󰑼𬁖孛, 󰰀擼󰜋方󰑼𬁖彗, 𡥵𤤰辰吏爫𤤰, 𡥵茄柴𫴶辰撅𦲿栘, 眉𫽄󱫩些時些吏𧿨衛...",Nom

In [38]:
# get the first using iloc -> dataframe
df_sample = df_article.iloc[1:2]
df_sample = df_sample.explode('sentences')
df_sample

                 Source sentences Label
1   10_nu-tu-tri_no.txt   吀𦖑㛪分觧𠳒尼   Nom
1   10_nu-tu-tri_no.txt  𢢇勾十女朱󰎾曰無   Nom
1   10_nu-tu-tri_no.txt   㤙生養似乎𡽫泰   Nom
1   10_nu-tu-tri_no.txt   捔𬚸昌庫𢚶報𡊰   Nom
1   10_nu-tu-tri_no.txt    虎拱男子偪𨕭   Nom
..                  ...       ...   ...
1   10_nu-tu-tri_no.txt  𡦂情𡦂孝於朱公平   Nom
1   10_nu-tu-tri_no.txt  扺朱塊𢢆拱𠊚𫏾   Nom
1   10_nu-tu-tri_no.txt   合道𡗶享福𨱽𥹰   Nom
1   10_nu-tu-tri_no.txt    清󰖆執整󰋇勾   Nom
1   10_nu-tu-tri_no.txt  埃𠸦拱隊唭𠑬辰唭   Nom

[107 rows x 3 columns]

In [37]:
# demo

# Create a sample DataFrame
data = {'A': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 'B': [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]}
df = pd.DataFrame(data)
print(df)
# Assign continuous partition values
df = Partitioner.assign_continuous_partition_values(df, 5, 'partition')

# Group the values in column 'B' by the partition values
grouped = Partitioner.group_partition(df, 'partition', 'B', delimiter=',')

print(grouped)

    A   B
0   1  11
1   2  12
2   3  13
3   4  14
4   5  15
5   6  16
6   7  17
7   8  18
8   9  19
9  10  20
  partition            B
0         0  12,13,14,15
1         1        16,17
2         2           18
3         3           19
4         4           20

C:\Users\Admin\AppData\Local\Temp\ipykernel_14148\2530702606.py:56: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grouped = df.groupby(group_column)[value_column].apply(lambda x: delimiter.join(map(str, x))).reset_index()

In [41]:
df_sample

                 Source sentences Label partition
1   10_nu-tu-tri_no.txt   吀𦖑㛪分觧𠳒尼   Nom         0
1   10_nu-tu-tri_no.txt  𢢇勾十女朱󰎾曰無   Nom         0
1   10_nu-tu-tri_no.txt   㤙生養似乎𡽫泰   Nom         0
1   10_nu-tu-tri_no.txt   捔𬚸昌庫𢚶報𡊰   Nom         0
1   10_nu-tu-tri_no.txt    虎拱男子偪𨕭   Nom         0
..                  ...       ...   ...       ...
1   10_nu-tu-tri_no.txt  𡦂情𡦂孝於朱公平   Nom         0
1   10_nu-tu-tri_no.txt  扺朱塊𢢆拱𠊚𫏾   Nom         0
1   10_nu-tu-tri_no.txt   合道𡗶享福𨱽𥹰   Nom         0
1   10_nu-tu-tri_no.txt    清󰖆執整󰋇勾   Nom         0
1   10_nu-tu-tri_no.txt  埃𠸦拱隊唭𠑬辰唭   Nom         0

[107 rows x 4 columns]

In [40]:
df_sample = Partitioner.assign_continuous_partition_values(df_sample, 5, 'partition')

# Group the valuesd in column 'B' by the partition values
grouped = Partitioner.group_partition(df, 'partition', 'sentences', delimiter=',')

print(grouped)

C:\Users\Admin\AppData\Local\Temp\ipykernel_14148\2530702606.py:56: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grouped = df.groupby(group_column)[value_column].apply(lambda x: delimiter.join(map(str, x))).reset_index()

KeyError: 'Column not found: sentences'